"""added role table

Revision ID: 2e7770adf04b
Revises: a2b3c4d5e6f7
Create Date: 2026-06-18 16:41:13.321686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2e7770adf04b'
down_revision: Union[str, None] = 'a2b3c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column(
        'role',
        sa.Enum('member', 'merchant', 'operator', name='user_role'),
        nullable=False,
        server_default='member',
    ))
    op.add_column('users', sa.Column(
        'is_merchant_approved',
        sa.Boolean(),
        nullable=False,
        server_default='false',
    ))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_merchant_approved')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
